---
- hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
      vars:
      ansible_user: ec2-user

- hosts: all
  var:
    ansible_user: ec2-user
  tasks:
    - name: Proceed with playbook
      ping:
