---
- hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user

- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
  - name: Install Apache httpd
    yum:
      name: httpd
      state: latest

  - name: Start Apache httpd
    service:
      name: httpd
      enabled: true
      state: started

  - name: Install App
    copy: 
      src: /home/sinensia/hello-2048/public_html/
      dest: /var/www/html/
      owner: apache
      group: apache
      mode: "0644"
      directory_mode: "0755"

